services:
    lapalabs_rating.subscriber.vote:
        class: LapaLabs\RatingBundle\EventSubscriber\VoteSubscriber
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber }
